export const GET_CHANNELS = "GET_CHANNELS";
export const FETCH_CHANNELS_REQUEST = "FETCH_CHANNELS_REQUEST";
export const FETCH_CHANNELS_SUCCESS = "FETCH_CHANNELS_SUCCESS";
export const FETCH_CHANNELS_FAILURE = "FETCH_CHANNELS_FAILURE";
export const ADD_NEW_CHANNEL = "ADD_NEW_CHANNEL";
